# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: use Nodejs 12.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    
    - name: debug ssh_key
      run: echo "${{ secrets.SERVER_SSH_KEY }}"

    - name: npm install 
      run: npm i

    - name: npm test
      run: npm run test


    - name: Set SSH Environment
      env:
        DOCS_DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DOCS_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      env: 
        DEPLOY_KEY_NAME: "deploy_key"
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
