# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Nodejs 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      - name: debug ssh_key
        run: echo "${{ secrets.SERVER_SSH_KEY }}"

      - name: npm install
        run: npm i

      - name: npm test
        run: npm run test

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist"
          target: "tmp/

      # - name: executing script via ssh password
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: cd video-platform-back-end && docker-compose down && docker-compose pull && docker-compose up -d
